version: "3.6"
services:
  vue:
    build:
      context: ./vue
      dockerfile: ./vue/Dockerfile
      networks:
        - webnet

  flask:
    build:
      context: ./flask
      dockerfile: ./flask/Dockerfile
      networks:
        - webnet

networks:
  webnet: