version: "3.6"

services:
  vue:
    build:
      context: ./vue/
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    networks:
      - webnet

  flask:
    build:
      context: ./flask/
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    networks:
      - webnet

networks:
  webnet: